fix up testall for angular

diff --git a/scripts/testall b/scripts/testall
--- a/scripts/testall
+++ b/scripts/testall
@@ -8,11 +8,33 @@ execdir=`dirname $0`
 [ "$execdir" = "" -o "$execdir" = "." ] && execdir=$PWD
 PACKAGE_DIR=`(cd $execdir/.. > /dev/null 2>&1; pwd)`
 
-$PACKAGE_DIR/scripts/setversion.sh
-(cd $PACKAGE_DIR/python && python setup.py build)
+# buildtypes="angular python"
+buildtypes="python"
 
-export OAR_PYTHONPATH=`ls -d $PACKAGE_DIR/python/build/lib.* | head -1`
-export OAR_JQ_LIB=$PACKAGE_DIR/oar-metadata/jq
-export OAR_MERGE_ETC=$PACKAGE_DIR/oar-metadata/etc/merge
-exec $PACKAGE_DIR/python/runtests.py
+dotypes="$@"
+[ -n "$dotypes" ] || dotypes=$buildtypes
 
+echo > testall.out
+
+fail=
+for bt in $dotypes; do
+    if [ -x "$execdir/testall.$bt" ]; then
+        echo "Running $bt tests..." | tee -a testall.out
+        echo >> testall.out
+        echo '+' "$execdir/testall.$bt" | tee -a testall.out
+        ("$execdir/testall.$bt"  || fail=$?) 2>&1 | tee -a testall.out
+    else
+        echo "Testing script for $bt does not exist!" | tee -a testall.out
+        fail=2
+    fi
+done
+
+if [ -n "$fail" ]; then
+    echo "Some test(s) failed" | tee -a testall.out
+    exit $fail
+else
+    echo "All OK" | tee -a testall.out
+fi
+exit 0
+
+        
